var request=new XMLHttpRequest();
request.open("GET","https://restcountries.com/v2/all");
request.send();
request.onload=function()
{
    var result=JSON.parse(request.response);
    for(var i=0;i<result.length;i++){
        console.log(result[i].flag);
        
    }
}
//Output:
// Live reload enabled.
// script.js:8 https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_the_Taliban.svg
// script.js:8 https://flagcdn.com/ax.svg
// script.js:8 https://flagcdn.com/al.svg
// script.js:8 https://flagcdn.com/dz.svg
// script.js:8 https://flagcdn.com/as.svg
// script.js:8 https://flagcdn.com/ad.svg
// script.js:8 https://flagcdn.com/ao.svg
// script.js:8 https://flagcdn.com/ai.svg
// script.js:8 https://flagcdn.com/aq.svg
// script.js:8 https://flagcdn.com/ag.svg
// script.js:8 https://flagcdn.com/ar.svg
// script.js:8 https://flagcdn.com/am.svg
// script.js:8 https://flagcdn.com/aw.svg
// script.js:8 https://flagcdn.com/au.svg
// script.js:8 https://flagcdn.com/at.svg
// script.js:8 https://flagcdn.com/az.svg
// script.js:8 https://flagcdn.com/bs.svg
// script.js:8 https://flagcdn.com/bh.svg
// script.js:8 https://flagcdn.com/bd.svg
// script.js:8 https://flagcdn.com/bb.svg
// script.js:8 https://flagcdn.com/by.svg
// script.js:8 https://flagcdn.com/be.svg
// script.js:8 https://flagcdn.com/bz.svg
// script.js:8 https://flagcdn.com/bj.svg
// script.js:8 https://flagcdn.com/bm.svg
// script.js:8 https://flagcdn.com/bt.svg
// script.js:8 https://flagcdn.com/bo.svg
// script.js:8 https://flagcdn.com/bq.svg
// script.js:8 https://flagcdn.com/ba.svg
// script.js:8 https://flagcdn.com/bw.svg
// script.js:8 https://flagcdn.com/bv.svg
// script.js:8 https://flagcdn.com/br.svg
// script.js:8 https://flagcdn.com/io.svg
// script.js:8 https://flagcdn.com/um.svg
// script.js:8 https://flagcdn.com/vg.svg
// script.js:8 https://flagcdn.com/vi.svg
// script.js:8 https://flagcdn.com/bn.svg
// script.js:8 https://flagcdn.com/bg.svg
// script.js:8 https://flagcdn.com/bf.svg
// script.js:8 https://flagcdn.com/bi.svg
// script.js:8 https://flagcdn.com/kh.svg
// script.js:8 https://flagcdn.com/cm.svg
// script.js:8 https://flagcdn.com/ca.svg
// script.js:8 https://flagcdn.com/cv.svg
// script.js:8 https://flagcdn.com/ky.svg
// script.js:8 https://flagcdn.com/cf.svg
// script.js:8 https://flagcdn.com/td.svg
// script.js:8 https://flagcdn.com/cl.svg
// script.js:8 https://flagcdn.com/cn.svg
// script.js:8 https://flagcdn.com/cx.svg
// script.js:8 https://flagcdn.com/cc.svg
// script.js:8 https://flagcdn.com/co.svg
// script.js:8 https://flagcdn.com/km.svg
// script.js:8 https://flagcdn.com/cg.svg
// script.js:8 https://flagcdn.com/cd.svg
// script.js:8 https://flagcdn.com/ck.svg
// script.js:8 https://flagcdn.com/cr.svg
// script.js:8 https://flagcdn.com/hr.svg
// script.js:8 https://flagcdn.com/cu.svg
// script.js:8 https://flagcdn.com/cw.svg
// script.js:8 https://flagcdn.com/cy.svg
// script.js:8 https://flagcdn.com/cz.svg
// script.js:8 https://flagcdn.com/dk.svg
// script.js:8 https://flagcdn.com/dj.svg
// script.js:8 https://flagcdn.com/dm.svg
// script.js:8 https://flagcdn.com/do.svg
// script.js:8 https://flagcdn.com/ec.svg
// script.js:8 https://flagcdn.com/eg.svg
// script.js:8 https://flagcdn.com/sv.svg
// script.js:8 https://flagcdn.com/gq.svg
// script.js:8 https://flagcdn.com/er.svg
// script.js:8 https://flagcdn.com/ee.svg
// script.js:8 https://flagcdn.com/et.svg
// script.js:8 https://flagcdn.com/fk.svg
// script.js:8 https://flagcdn.com/fo.svg
// script.js:8 https://flagcdn.com/fj.svg
// script.js:8 https://flagcdn.com/fi.svg
// script.js:8 https://flagcdn.com/fr.svg
// script.js:8 https://flagcdn.com/gf.svg
// script.js:8 https://flagcdn.com/pf.svg
// script.js:8 https://flagcdn.com/tf.svg
// script.js:8 https://flagcdn.com/ga.svg
// script.js:8 https://flagcdn.com/gm.svg
// script.js:8 https://flagcdn.com/ge.svg
// script.js:8 https://flagcdn.com/de.svg
// script.js:8 https://flagcdn.com/gh.svg
// script.js:8 https://flagcdn.com/gi.svg
// script.js:8 https://flagcdn.com/gr.svg
// script.js:8 https://flagcdn.com/gl.svg
// script.js:8 https://flagcdn.com/gd.svg
// script.js:8 https://flagcdn.com/gp.svg
// script.js:8 https://flagcdn.com/gu.svg
// script.js:8 https://flagcdn.com/gt.svg
// script.js:8 https://flagcdn.com/gg.svg
// script.js:8 https://flagcdn.com/gn.svg
// script.js:8 https://flagcdn.com/gw.svg
// script.js:8 https://flagcdn.com/gy.svg
// script.js:8 https://flagcdn.com/ht.svg
// script.js:8 https://flagcdn.com/hm.svg
// script.js:8 https://flagcdn.com/va.svg
// script.js:8 https://flagcdn.com/hn.svg
// script.js:8 https://flagcdn.com/hu.svg
// script.js:8 https://flagcdn.com/hk.svg
// script.js:8 https://flagcdn.com/is.svg
// script.js:8 https://flagcdn.com/in.svg
// script.js:8 https://flagcdn.com/id.svg
// script.js:8 https://flagcdn.com/ci.svg
// script.js:8 https://flagcdn.com/ir.svg
// script.js:8 https://flagcdn.com/iq.svg
// script.js:8 https://flagcdn.com/ie.svg
// script.js:8 https://flagcdn.com/im.svg
// script.js:8 https://flagcdn.com/il.svg
// script.js:8 https://flagcdn.com/it.svg
// script.js:8 https://flagcdn.com/jm.svg
// script.js:8 https://flagcdn.com/jp.svg
// script.js:8 https://flagcdn.com/je.svg
// script.js:8 https://flagcdn.com/jo.svg
// script.js:8 https://flagcdn.com/kz.svg
// script.js:8 https://flagcdn.com/ke.svg
// script.js:8 https://flagcdn.com/ki.svg
// script.js:8 https://flagcdn.com/kw.svg
// script.js:8 https://flagcdn.com/kg.svg
// script.js:8 https://flagcdn.com/la.svg
// script.js:8 https://flagcdn.com/lv.svg
// script.js:8 https://flagcdn.com/lb.svg
// script.js:8 https://flagcdn.com/ls.svg
// script.js:8 https://flagcdn.com/lr.svg
// script.js:8 https://flagcdn.com/ly.svg
// script.js:8 https://flagcdn.com/li.svg
// script.js:8 https://flagcdn.com/lt.svg
// script.js:8 https://flagcdn.com/lu.svg
// script.js:8 https://flagcdn.com/mo.svg
// script.js:8 https://flagcdn.com/mk.svg
// script.js:8 https://flagcdn.com/mg.svg
// script.js:8 https://flagcdn.com/mw.svg
// script.js:8 https://flagcdn.com/my.svg
// script.js:8 https://flagcdn.com/mv.svg
// script.js:8 https://flagcdn.com/ml.svg
// script.js:8 https://flagcdn.com/mt.svg
// script.js:8 https://flagcdn.com/mh.svg
// script.js:8 https://flagcdn.com/mq.svg
// script.js:8 https://flagcdn.com/mr.svg
// script.js:8 https://flagcdn.com/mu.svg
// script.js:8 https://flagcdn.com/yt.svg
// script.js:8 https://flagcdn.com/mx.svg
// script.js:8 https://flagcdn.com/fm.svg
// script.js:8 https://flagcdn.com/md.svg
// script.js:8 https://flagcdn.com/mc.svg
// script.js:8 https://flagcdn.com/mn.svg
// script.js:8 https://flagcdn.com/me.svg
// script.js:8 https://flagcdn.com/ms.svg
// script.js:8 https://flagcdn.com/ma.svg
// script.js:8 https://flagcdn.com/mz.svg
// script.js:8 https://flagcdn.com/mm.svg
// script.js:8 https://flagcdn.com/na.svg
// script.js:8 https://flagcdn.com/nr.svg
// script.js:8 https://flagcdn.com/np.svg
// script.js:8 https://flagcdn.com/nl.svg
// script.js:8 https://flagcdn.com/nc.svg
// script.js:8 https://flagcdn.com/nz.svg
// script.js:8 https://flagcdn.com/ni.svg
// script.js:8 https://flagcdn.com/ne.svg
// script.js:8 https://flagcdn.com/ng.svg
// script.js:8 https://flagcdn.com/nu.svg
// script.js:8 https://flagcdn.com/nf.svg
// script.js:8 https://flagcdn.com/kp.svg
// script.js:8 https://flagcdn.com/mp.svg
// script.js:8 https://flagcdn.com/no.svg
// script.js:8 https://flagcdn.com/om.svg
// script.js:8 https://flagcdn.com/pk.svg
// script.js:8 https://flagcdn.com/pw.svg
// script.js:8 https://flagcdn.com/ps.svg
// script.js:8 https://flagcdn.com/pa.svg
// script.js:8 https://flagcdn.com/pg.svg
// script.js:8 https://flagcdn.com/py.svg
// script.js:8 https://flagcdn.com/pe.svg
// script.js:8 https://flagcdn.com/ph.svg
// script.js:8 https://flagcdn.com/pn.svg
// script.js:8 https://flagcdn.com/pl.svg
// script.js:8 https://flagcdn.com/pt.svg
// script.js:8 https://flagcdn.com/pr.svg
// script.js:8 https://flagcdn.com/qa.svg
// script.js:8 https://flagcdn.com/xk.svg
// script.js:8 https://flagcdn.com/re.svg
// script.js:8 https://flagcdn.com/ro.svg
// script.js:8 https://flagcdn.com/ru.svg
// script.js:8 https://flagcdn.com/rw.svg
// script.js:8 https://flagcdn.com/bl.svg
// script.js:8 https://flagcdn.com/sh.svg
// script.js:8 https://flagcdn.com/kn.svg
// script.js:8 https://flagcdn.com/lc.svg
// script.js:8 https://flagcdn.com/mf.svg
// script.js:8 https://flagcdn.com/pm.svg
// script.js:8 https://flagcdn.com/vc.svg
// script.js:8 https://flagcdn.com/ws.svg
// script.js:8 https://flagcdn.com/sm.svg
// script.js:8 https://flagcdn.com/st.svg
// script.js:8 https://flagcdn.com/sa.svg
// script.js:8 https://flagcdn.com/sn.svg
// script.js:8 https://flagcdn.com/rs.svg
// script.js:8 https://flagcdn.com/sc.svg
// script.js:8 https://flagcdn.com/sl.svg
// script.js:8 https://flagcdn.com/sg.svg
// script.js:8 https://flagcdn.com/sx.svg
// script.js:8 https://flagcdn.com/sk.svg
// script.js:8 https://flagcdn.com/si.svg
// script.js:8 https://flagcdn.com/sb.svg
// script.js:8 https://flagcdn.com/so.svg
// script.js:8 https://flagcdn.com/za.svg
// script.js:8 https://flagcdn.com/gs.svg
// script.js:8 https://flagcdn.com/kr.svg
// script.js:8 https://flagcdn.com/es.svg
// script.js:8 https://flagcdn.com/lk.svg
// script.js:8 https://flagcdn.com/sd.svg
// script.js:8 https://flagcdn.com/ss.svg
// script.js:8 https://flagcdn.com/sr.svg
// script.js:8 https://flagcdn.com/sj.svg
// script.js:8 https://flagcdn.com/sz.svg
// script.js:8 https://flagcdn.com/se.svg
// script.js:8 https://flagcdn.com/ch.svg
// script.js:8 https://flagcdn.com/sy.svg
// script.js:8 https://flagcdn.com/tw.svg
// script.js:8 https://flagcdn.com/tj.svg
// script.js:8 https://flagcdn.com/tz.svg
// script.js:8 https://flagcdn.com/th.svg
// script.js:8 https://flagcdn.com/tl.svg
// script.js:8 https://flagcdn.com/tg.svg
// script.js:8 https://flagcdn.com/tk.svg
// script.js:8 https://flagcdn.com/to.svg
// script.js:8 https://flagcdn.com/tt.svg
// script.js:8 https://flagcdn.com/tn.svg
// script.js:8 https://flagcdn.com/tr.svg
// script.js:8 https://flagcdn.com/tm.svg
// script.js:8 https://flagcdn.com/tc.svg
// script.js:8 https://flagcdn.com/tv.svg
// script.js:8 https://flagcdn.com/ug.svg
// script.js:8 https://flagcdn.com/ua.svg
// script.js:8 https://flagcdn.com/ae.svg
// script.js:8 https://flagcdn.com/gb.svg
// script.js:8 https://flagcdn.com/us.svg
// script.js:8 https://flagcdn.com/uy.svg
// script.js:8 https://flagcdn.com/uz.svg
// script.js:8 https://flagcdn.com/vu.svg
// script.js:8 https://flagcdn.com/ve.svg
// script.js:8 https://flagcdn.com/vn.svg
// script.js:8 https://flagcdn.com/wf.svg
// script.js:8 https://flagcdn.com/eh.svg
// script.js:8 https://flagcdn.com/ye.svg
// script.js:8 https://flagcdn.com/zm.svg
